import type { Metadata } from "next";
import "../../../globals.css";

export const metadata: Metadata = {
  title: "Menu - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-fit gap-2 mt-10">
        <div className="mx-14 px-2 py-3 border-b">
            <h1 className="text-3xl font-semibold">Menu</h1>
            <p className="text-neutral-400 text-xl">Manage you restaurant menu.</p>
        </div>
        <div className="flex h-full mx-12 gap-2 px-3">
            {children}
        </div>
    </div>
  );
}
