import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "DesiTadka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>{children}</section>
  );
}
