import type { Metadata } from "next";
import "../globals.css";
import { currentUser } from "@clerk/nextjs/server";
import { getUserByUserId, PostUser } from "@/lib/actions/UserActions";

export const metadata: Metadata = {
  title: "DesiTadka",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const userdata = await getUserByUserId(user?.id+"");
    if(!userdata){
      await PostUser({
        name: user?.fullName ? user?.fullName+"" : user?.username+"",
        userId: user?.id + "",
        email: user?.emailAddresses[0].emailAddress + "",
        image: user?.imageUrl + ""
      })
    }
  return (
    <section>{children}</section>
  );
}
