import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/components/customer/Footer";
import NavBar from "@/components/customer/NavBar";
import { Toaster } from "@/components/ui/toaster";
import { currentUser } from "@clerk/nextjs/server";
import { getUserByUserId, PostUser } from "@/lib/actions/UserActions";

export const metadata: Metadata = {
  title: "OrderEase",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const userdata = await getUserByUserId(user?.id+"");
    if(!userdata){
      await PostUser({
        name: user?.fullName ? user?.fullName+"" : user?.username+"",
        userId: user?.id + "",
        email: user?.emailAddresses[0].emailAddress + "",
        image: user?.imageUrl + ""
      })
    }
  return (
    <section className="w-screen ">
      <Toaster />
      <NavBar/>
      {children}
      <Footer/>
    </section>
  );
}
