import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/components/customer/Footer";
import NavBar from "@/components/customer/NavBar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "OrderEase - About our team",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-screen ">
      <Toaster />
      <NavBar/>
      {children}
      <Footer/>
    </section>
  );
}
