import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { getUserByUserId, getUserId, PostUser } from "@/lib/actions/UserActions";
import { redirect } from "next/navigation";
import { currentUser } from "@clerk/nextjs/server";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  if(!user?.id) redirect("/sign-in");
  else{
    const userdata = await getUserByUserId(user?.id+"");
    if(!userdata){
      await PostUser({
        name: user.fullName ? user.fullName+"" : user.username+"",
        userId: user.id,
        email: user.emailAddresses[0].emailAddress,
        image: user.imageUrl
      })
    }
  }
  return (
    <html lang="en">
      <ClerkProvider>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased  overflow-x-hidden",
          fontSans.variable
        )}
      >
        {children}
      </body>
      </ClerkProvider>
    </html>
  );
}
