import type { Metadata } from "next";
import "../../globals.css";
import Navbar from "@/components/restaurant/dashboard/Navbar";

export const metadata: Metadata = {
  title: "DesiTadka-Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
        <Navbar/>
        {children}
    </section>
  );
}
