import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Auth - OrderEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-screen h-screen flex justify-center items-center">
      {children}
    </section>
  );
}
