import type { Metadata } from "next";
import "../../../globals.css";
import Navbar from "@/components/restaurant/dashboard/Navbar";
import Sidebar from "@/components/restaurant/dashboard/Settings/Sidebar";

export const metadata: Metadata = {
  title: "Settings - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-fit gap-2 mt-10">
        <div className="mx-14 px-2 py-3 border-b">
            <h1 className="text-3xl font-semibold">Settings</h1>
            <p className="text-neutral-400 text-xl">Manage you restaurant settings.</p>
        </div>
        <div className="flex h-full mx-12 gap-2 pr-2">
            <Sidebar/>
            {children}
        </div>
    </div>
  );
}
